#how to use ROCR
#it can do a lot of goodness of fit tests and give you a good graphical view of the data you are working with

#prediction()
#use this to make a predidction object for the performance() function to plot in ROCR


pred <- prediction(p93, air$event)

#The first argument is a set of predicted values, in this case generated with the default predict() command
#the 2nd argument is the set of true labels, which is true observations of the dichotomous varialbe. 
#the two arguments must be the same size. 
#reading the ?prediction page will be helpful

#performance()
#this is used to check the performance of your prediction. It accepts a prediction object, generated by prediction()
#and then other arguments from a wide list of useful things. Check the ?performance page for the full list

perf <- performance(pred, "tpr", "fpr")
plot(perf)

perf1 <- performance(pred, "sens", "spec")
plot(perf1)

perf2 <- performance(pred, "auc") #area under ROC curve
perf2

perf3 <- performance(pred, "acc") #accuracy against cutoff
plot(perf3)

predict1 <- predict(m2, type="response")
predict2 <- prediction(predict1, air$event)
perf4 <- performance(predict2, "auc")
perf4

library(verification)
roc.plot(air$event, p93)

#Hosmer lemeshow test
library(ResourceSelection)

h1 <- hoslem.test(air$event,fitted(m93), g=10)
?hoslem.test
h1
p93_fix <- predict(m93, type="response")
asdf <- cbind(h1$expected, h1$observed)
class(asdf)
asdf

h2 <- hoslem.test(air$event, p1, g=10)
h2
asdf1 <- cbind(h2$expected, h2$observed)
class(asdf)
asdf1

h3 <- hoslem.test(air$event, pm2, g=10)
h3
pm2 <- predict(m2, type="response")

hos <- cbind(h3$expected, h3$observed)
hos



#correlation stuff
air2 <- data.frame(air$event, air$three_day_PM, air$five_day_O3, air$five_day_NO2, air$SO2_NO2, air$O3_NO2)
cor(air2)
